plugins {
    id 'java'
    id 'com.gradleup.shadow' version "9.4.1" // for shadowing
}

apply from: rootDir.toString() + '/dependencies.gradle'

group = properties['group']
version = properties['version']

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(25))
}

ext {
    pluginMain = properties['plugin.main'] == 'default' ?
            "${project.group}.${project.name.toLowerCase()}.${project.name}" :
            properties['plugin.main']
}

repositories {
    mavenCentral()
    maven {
        url = 'https://hub.spigotmc.org/nexus/content/repositories/snapshots/'

        // As of Gradle 5.1, you can limit this to only those
        // dependencies you expect from it
        content {
            includeGroup 'org.bukkit'
            includeGroup 'org.spigotmc'
        }
    }
    maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url = 'https://oss.sonatype.org/content/repositories/central' }
    maven {
        name = "sonatype"
        url = "https://oss.sonatype.org/content/groups/public/"
    }
    maven {
        name = "streamline-essentials"
        url = "https://repo.codemc.org/repository/streamline-essentials/"
    }
    maven { url = "https://jitpack.io" }
    maven {
        name = "placeholderapi"
        url = "https://repo.extendedclip.com/content/repositories/placeholderapi/"
    }
    maven { url = 'https://repo.papermc.io/repository/maven-snapshots/' }
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }
}

dependencies {
    // Defaults.
    compileOnly(files(FILES))
    annotationProcessor(ANNO)
    implementation(IMPL)
    compileOnly(COMP_ONLY)
    shadow(SHADOW)

    // Other Plugins
    compileOnly(OTHER_PLUGINS)
}

def pluginName = project.name
def pluginVersion = project.version.toString()
def pluginMainClass = project.ext.pluginMain

processResources {
    // Debugging: Print values
    doFirst {
        println "Version: ${pluginVersion}, Name: ${pluginName}, Main: ${pluginMainClass}"
    }

    inputs.property('name', pluginName)
    inputs.property('version', pluginVersion)
    inputs.property('main', pluginMainClass)

    filesMatching('**/plugin.yml') {
        expand (
                'name': pluginName,
                'version': pluginVersion,
                'main': pluginMainClass,
        )
    }
}

shadowJar {
    archiveClassifier.set('')

    buildDir = "target/"
    archiveFileName = "${project.name}-${project.version}.jar"

    minimize()
}

tasks.assemble {
    dependsOn(shadowJar)
}

wrapper {
    gradleVersion = '9.2.1'
    distributionType = Wrapper.DistributionType.ALL
}