# Id configurations.
ids:
  # The Server ID.
  # Use this to allow players to use the same minimap on this server or network.
  server: 10000

# Channel configurations.
channels:
  # The World Map channel.
  world-map:
    # The main channel.
    main: "xaeroworldmap:main"
  minimap:
    # The main channel.
    main: "xaerominimap:main"